// styles.js

import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  image: {
    width: 100,
    height: 100,
    position: 'absolute',
  },
  upperLeft: {
    top: 10,
    left: 10,
  },
  lowerRight: {
    bottom: 10,
    right: 10,
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  logomoniinter:{
    width: 30,
    height: 30,
    minWidth: 50,
    minHeight: 50,
    maxWidthidth: 50,
    maxHeighteight: 100,
    marginTop:-10
  },
  logomoni:{
    width: 100,
    height: 100,
    minWidth: 100,
    minHeight: 100,
    maxWidthidth: 100,
    maxHeighteight: 100,
    textAlign:'center',
    alignContent:'center',
    margin:10,
    marginLeft:15,
  },
  logomoniperfil:{
    width: 150,
    height: 150,
    minWidth: 100,
    minHeight: 100,
    maxWidthidth: 100,
    maxHeighteight: 100,
    textAlign:'center',
    alignItems: 'center',
    justifyContent: 'center',
    margin:20,
    left:13,
  },
  logomoni2:{
    width: 100,
    height: 100,
    minWidth: 100,
    minHeight: 100,
    maxWidthidth: 100,
    maxHeighteight: 100,
    textAlign:'center',
    alignContent:'center',
    opacity: 0.1,
    margin:20,
    marginLeft:15,
  },
  logoagua:{
    width: 140,
    height: 110,
    minWidth: 100,
    minHeight: 100,
    maxWidthidth: 100,
    maxHeighteight: 100,
    textAlign:'center',
    alignContent:'center',
    marginTop:5,
  },
  logonivel:{
    width: 100,
    height: 150,
    minWidth: 100,
    minHeight: 100,
    maxWidthidth: 100,
    maxHeighteight: 100,
    textAlign:'center',
    alignContent:'center',
    margin:10,
    marginLeft:20,
  },
  logo: {
    width: 100,
    height: 100,
  },
  title: {
    fontSize: 24,
    marginBottom: 16,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
  },
  input: {
    height: 40,
    borderColor: '#FEFEFC',
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 8,
    borderRadius: 10,
    color: '#FEFEFC',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 50,
    elevation: 3,
    backgroundColor: 'green',
    marginBottom: 12,
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
  textRecuperar: {
    textAlign: 'center',
    fontSize: 17.5,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: 'white',
  },
  textRegistro1: {
    fontSize: 17.5,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: 'white',
    marginTop: 50,
  },
  textRegistro: {
    fontSize: 17.5,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'blue',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#FEFEFC',
    borderWidth: 1,
    marginBottom: 12,
    borderRadius: 10,
  },
  passwordInput: {
    flex: 1,
    height: 40,
    paddingHorizontal: 8,
    color: '#FEFEFC',
  },
  eyeIcon: {
    marginRight: 10,
  },
  waveSvg: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: -1,
  },
  wavesContainer: {
    width: '100%',
    overflow: 'hidden',
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  waves: {
    width: 100,
    height: 100,
    backgroundColor: 'rgba(255,255,255,0.7)',
    position: 'absolute',
    bottom: 0,
  },
  backButton1: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    backgroundColor: '#4CAF50',
    borderRadius: 10,
    padding: 10,
    margin: 10,
    textAlign: 'center',
    top: 0,
    left: 5
  },
});
